dist: xenial

language: go

env: SERVICE_ENVIRONMENT=test

go:
  - 1.11.5

git:
  depth: 1

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$PATH"

notifications:
  email: false

script:
  - go test -v -race ./...