dist: xenial

language: go

env: SERVICE_ENVIRONMENT=test GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.11.5

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - go test -v -race ./...